### ISSUE TITLE
Page not found (404)

### ISSUE THREAD

**Issue by zfrenchee** [machinalis/iepy#92]
I've been following the "From 0 to IEPY" tutorial. I've loaded the data, run preprocess, and now I'm trying to [Open the web interface](http://iepy.readthedocs.org/en/latest/tutorial.html#open-the-web-interface). 

The first time I run `python bin/manage.py runserver` it says I need to run a migration first. I do. 

Then, I try to `runserver` again, and I get some promising output:

```
System check identified no issues (0 silenced).
February 15, 2016 - 17:17:58
Django version 1.9.2, using settings 'my-project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

But as soon as I go to http://127.0.0.1:8000/ I get:

```
Page not found (404)
Request Method:	GET
Request URL:	http://localhost:8000/admin/login?next=/
Using the URLconf defined in webui.urls, Django tried these URL patterns, in this order:
^$ [name='home']
^admin/ ^$ [name='index']
^admin/ ^login/$ [name='login']
^admin/ ^logout/$ [name='logout']
^admin/ ^password_change/$ [name='password_change']
^admin/ ^password_change/done/$ [name='password_change_done']
^admin/ ^jsi18n/$ [name='jsi18n']
^admin/ ^r/(?P<content_type_id>\d+)/(?P<object_id>.+)/$ [name='view_on_site']
^admin/ ^corpus/relation/
^admin/ ^auth/user/
^admin/ ^corpus/entity/
^admin/ ^corpus/iedocument/
^admin/ ^corpus/gazetteitem/
^admin/ ^auth/group/
^admin/ ^corpus/entitykind/
^admin/ ^corpus/iedocumentmetadata/
^admin/ ^corpus/entityoccurrence/
^admin/ ^(?P<app_label>corpus|auth)/$ [name='app_list']
^corpus/
The current URL, admin/login, didn't match any of these.
```

What's going on?

**Comment by jmansilla** [comment]
Hi there.

I'm not sure whats going on.

I just made a try locally creating a new IEPY instance, and just after that starting the server, and I didnt have any problems.

When I went to such url (http://localhost:8000/) I was redirected to http://localhost:8000/admin/login?next=/ from where I logged in.

Two questions:
 - what iepy version are you using?
 - Can you make a try creating a new iepy instance, and without doing anything else start the server and attempt to log in?

**Comment by askmyhat** [comment]
Have the same problem but there wasn't a message about migration
IEPY 0.9.5

**Comment by jmansilla** [comment]
Hello People.

I still cant reproduce this, so I'm not completely sure what's happening to you.
Under what environment are you working on? Linux, Max? Version?

Question/Tip (just in case): did you try 127.0.0.1 instead of localhost?

**Comment by jmansilla** [comment]
Extra: can you paste in here the logging/output of the server after you attempt to access the website?

**Comment by askmyhat** [comment]
Ubuntu 15.04
Python 3.5.1
IEPY 0.9.5
Django 1.9.4
Sklearn 0.17.1
NLTK 3.2
With that configuration I can run the server.

Following installation guide from docs I ran "pip install iepy"
Running iepy command returns "can't set attribute" error in
.../python3.5/site-packages/nltk/internals.py
`parsed_pattern.pattern.groups = 1`
Upgrading NLTK to latest version solved that problem.

Then I modified imports in
.../python3.5/site-packages/iepy/preprocess/tagger.py
```
- from nltk.tag.stanford import POSTagger
+ from nltk.tag.stanford import StanfordPOSTagger as POSTagger
```
and in
.../python3.5/site-packages/iepy/preprocess/ner/stanford.py
```
- from nltk.tag.stanford import NERTagger
+ from nltk.tag.stanford import StanfordNERTagger as NERTagger
```

Now I can run iepy command but creating a project with "iepy --create test" return error after specifying database name
"module 'html.parser' has no attribute 'HTMLParseError'"
in .../python3.5/site-packages/django/utils/html_parser.py"
`HTMLParseError = _html_parser.HTMLParseError`
Upgrading Django to latest version solved that problem.

I did not need to run migration and started the server.
Going to http://127.0.0.1:8000/ redirects me to http://127.0.0.1:8000/admin/login?next=

> Page not found (404)
> Request Method:	GET
> Request URL:	http://127.0.0.1:8000/admin/login?next=/
> Using the URLconf defined in webui.urls, Django tried these URL patterns, in this order:
> ^$ [name='home']
> ^admin/ ^$ [name='index']
> ^admin/ ^login/$ [name='login']
> ^admin/ ^logout/$ [name='logout']
> ^admin/ ^password_change/$ [name='password_change']
> ^admin/ ^password_change/done/$ [name='password_change_done']
> ^admin/ ^jsi18n/$ [name='jsi18n']
> ^admin/ ^r/(?P<content_type_id>\d+)/(?P<object_id>.+)/$ [name='view_on_site']
> ^admin/ ^auth/user/
> ^admin/ ^corpus/entitykind/
> ^admin/ ^auth/group/
> ^admin/ ^corpus/entityoccurrence/
> ^admin/ ^corpus/iedocumentmetadata/
> ^admin/ ^corpus/relation/
> ^admin/ ^corpus/entity/
> ^admin/ ^corpus/gazetteitem/
> ^admin/ ^corpus/iedocument/
> ^admin/ ^(?P<app_label>auth|corpus)/$ [name='app_list']
> ^corpus/
> The current URL, admin/login, didn't match any of these.

http://127.0.0.1:8000/admin/login/ returns "cannot import name 'import_by_path'" error which means upgrading django wasn't good idea.

**Comment by askmyhat** [comment]
Downgrading django to 1.8 is solution for me

**Comment by jmansilla** [comment]
Thanks for letting me know.
It's strange, because it's pinned to Django 1.7 (glad to see that it's at least working on 1.8)

I didn't realize yet that you people were using a higher Django version.  IEPY installation brought django 1.9, or you hand installed it? 
Is there a special need for having it on such version? 

Thanks for your reports

**Comment by askmyhat** [comment]
I am not sure about @zfrenchee's configuration.
IEPY installation brought me Django 1.7.x. I did manual upgrade of it to the latest version.

**Comment by jmansilla** [comment]
No further activity here. Closing for now.

For the record, iepy UI is working on Django 1.7 and there's no planned upgrade (although pull requests will be happily accepted)
